chore: confirm ci issue comes from coverage
okp4/discord-bot pull request #120
Opened 2022-11-16 09:01 UTC by ad2ien

2022-11-16 13:39 UTC, bdeneux requested changes

2022-11-17 07:32 UTC, ad2ien commented
@bdeneux I finally almost set it back like it was... but now I know why 😉

2022-11-17 08:47 UTC, bdeneux approved these changes
🎉 Thanks for the fix 🙏
Very strange that cargo make doesn't install the rust component but is not the first time that cargo make is not working well :/

2022-11-17 10:42 UTC, amimart approved these changes

2022-11-17 13:51 UTC, merged