Feat: Dockerfile
okp4/discord-bot pull request #9
Opened 2022-08-02 16:35 UTC by ingvaar

Add a Dockerfile and CI workflows related to Docker build/publish.

Docker build can be triggered via `cargo make docker`. It will build the image `discord-bot:latest`.

Because of the use of an `ENTRYPOINT` in the Dockerfile, you can simply run it with arguments required for the bot to start.
Example:
`docker run discord-bot:latest -t $TOKEN -g $GUILD_ID`

2022-08-02 19:33 UTC, ccamel approved these changes
LGTM! Thx 😊

2022-08-03 06:01 UTC, bdeneux approved these changes

2022-08-03 12:38 UTC, amimart requested changes
Great work, thank you!

I noticed some inconsistencies on the publish workflow, this is minor 😉

2022-08-03 12:38 UTC, amimart commented on .github/workflows/publish.yml
> +
```suggestion
```

Used to generate the image tag for PR, but not needed as we publish only main builds

2022-08-03 12:38 UTC, amimart commented on .github/workflows/publish.yml
> +            type=raw,enable=${{ !endsWith(github.ref, github.event.repository.default_branch) }},value=${{ env.CI_ACTION_REF_NAME_SLUG }}
```suggestion
```

Not needed as we publish only main builds

2022-08-03 12:50 UTC, amimart approved these changes

2022-08-03 13:12 UTC, merged