Ci: update dependencies
okp4/discord-bot pull request #98
Opened 2022-11-02 10:40 UTC by ad2ien

Update CI dependencies and add branch publish on comment.

2022-11-02 12:49 UTC, bdeneux approved these changes

2022-11-02 13:26 UTC, ccamel requested changes

2022-11-02 13:26 UTC, ccamel commented on .github/workflows/publish.yml
> +          toolchain: 1.64
If you update the toolchain, you must align this version everywhere, i.e.: `Dockerfile` and the `Cargo.toml`

2022-11-02 13:49 UTC, ad2ien commented
@ccamel toolchain of the project is aligned with CI's one. Now we'll need to merge this one before : https://github.com/okp4/discord-bot/pull/97

2022-11-02 16:49 UTC, ccamel approved these changes

2022-11-03 09:16 UTC, ingvaar approved these changes

2022-11-03 09:16 UTC, merged